---
title: "dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)
```

Loading the dataset and Data cleaning

```{r}
data("rest_inspec")
nyc_inspections_cleaned = rest_inspec %>%
  mutate(score = as.numeric(score), 
         inspection_date = as.Date(inspection_date),
         boro = as.factor(boro)) %>%
  select(boro,inspection_date,score) %>%
  filter(!is.na(score) & !is.na(boro) & !is.na(inspection_date)) %>%
  distinct()%>%
  sample_n(1000)
```


Column {data-width=650}
-----------------------------------------------------------------------

### Chart A--- Scatterplot

```{r}
nyc_inspections_cleaned %>%
  mutate(text_label = str_c("Borough:", boro, "\nScore:", score))%>%
  plot_ly(x = ~inspection_date, y = ~score, type = 'scatter', mode = 'markers',
           text = ~text_label, alpha = 0.5) %>%
  layout(title = "Scatterplot of Scores Over Inspection Dates",
         xaxis = list(title = "Inspection Date"),
         yaxis = list(title = "Score"))

```


Column {data-width=350}
-----------------------------------------------------------------------

### Chart B---Box plot

```{r}
nyc_inspections_cleaned %>%
  mutate(boro = fct_reorder(boro, score)) %>%
  plot_ly(y = ~score, color = ~boro, type = "box", colors = "viridis")%>%
  layout(title = "Boxplot of Scores by Borough",
         xaxis = list(title = "Borough"),
         yaxis = list(title = "Score"))
```


### Chart C--- Bar plot

```{r}
nyc_inspections_cleaned %>% 
  count(boro) %>%
  mutate(boro = fct_reorder(boro, n)) %>%
  plot_ly(x = ~boro, y = ~n, color = ~boro, type = "bar", colors = "viridis")%>%
  layout(title = "Count of Inspections by Borough",
         xaxis = list(title = "Borough"),
         yaxis = list(title = "Inspection Count"))
```




