---
title: "plotly"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)
```

Loading the dataset

```{r}
library(httr)
library(jsonlite)

get_all_inspections = function(url) {
  
  all_inspections = vector("list", length = 0)
  
  loop_index = 1
  chunk_size = 50000
  DO_NEXT = TRUE
  
  while (DO_NEXT) {
    message("Getting data, page ", loop_index)
    
    all_inspections[[loop_index]] = 
      GET(url,
          query = list(`$order` = "zipcode",
                       `$limit` = chunk_size,
                       `$offset` = as.integer((loop_index - 1) * chunk_size)
                       )
          ) %>%
      content("text") %>%
      fromJSON() %>%
      as_tibble()
    
    DO_NEXT = dim(all_inspections[[loop_index]])[1] == chunk_size
    loop_index = loop_index + 1
  }
  
  all_inspections
  
}

url = "https://data.cityofnewyork.us/resource/43nn-pn8j.json"

nyc_inspections = 
  get_all_inspections(url) %>%
  bind_rows() 
```
Data cleaning

```{r}
nyc_inspections_cleaned = nyc_inspections %>%
  mutate(score = as.numeric(score), 
         inspection_date = as.Date(inspection_date),
         grade_date = as.Date(grade_date),
         record_date = as.Date(record_date)) %>%
  filter(!is.na(score) & !is.na(boro) & !is.na(inspection_date)) %>%
  distinct()
nyc_inspections_cleaned
```


Column {data-width=650}
-----------------------------------------------------------------------

### Chart A--- Scatterplot

```{r}
nyc_inspections_cleaned %>%
  mutate(text_label = str_c("Borough:", boro, "\nScore:", score))%>%
  plot_ly(x = ~inspection_date, y = ~score, type = 'scatter', mode = 'markers',
          color = ~score, text = ~text_label, alpha = 0.5) %>%
  layout(title = "Scatterplot of Scores Over Inspection Dates",
         xaxis = list(title = "Inspection Date"),
         yaxis = list(title = "Score"))

```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B---Box plot

```{r}
nyc_inspections_cleaned %>%
  mutate(boro = fct_reorder(boro, score)) %>%
  plot_ly(y = ~score, color = ~boro, type = "box", colors = "viridis")%>%
  layout(title = "Boxplot of Scores by Borough",
         xaxis = list(title = "Borough"),
         yaxis = list(title = "Score"))
```

### Chart C--- Bar plot

```{r}
nyc_inspections_cleaned %>% 
  count(boro) %>%
  mutate(boro = fct_reorder(boro, n)) %>%
  plot_ly(x = ~boro, y = ~n, color = ~boro, type = "bar", colors = "viridis")%>%
  layout(title = "Count of Inspections by Borough",
         xaxis = list(title = "Borough"),
         yaxis = list(title = "Inspection Count"))
```

